---
# Copyright 2015, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generate a list of services
- stat: path=/etc/exports
  register: exports_exists
  always_run: yes
  tags:
    - cat1
    - cat2
    - cat3

- name: V-38677 - The NFS server must not have the insecure file locking option enabled.
  when: exports_exists.stat.exists == True
  replace:
    dest: /etc/exports
    regexp: 'insecure_locks'
  tags:
    - cat1
    - V-38677
    - nfs
