- name: V-38607 High  The SSH daemon must be configured to use only the SSHv2 protocol
  lineinfile: state=present dest=/etc/ssh/sshd_config regexp='^(#)?Protocol \d' line='Protocol 2'
  notify: restart ssh
  tags: [ 'ssh' , 'cat1' , 'V-38607' , 'ssh' ]

- name: V-38614 High  The SSH daemon must not allow authentication using an empty password
  lineinfile: state=present dest=/etc/ssh/sshd_config regexp='^(#)?PermitEmptyPasswords' line='PermitEmptyPasswords no'
  notify: restart ssh
  tags: [ 'ssh' , 'cat1' , 'V-38614' , 'ssh' ]